handlebars:
  suffix: .html

server:
  tomcat:
    # 대기열의 최대 길이.
    # 커넥션 최대 개수를 넘어갔을 때 또 연결 요청이 온다면 해당 요청은 대기열 큐에 보관된다.
    # 대기열도 가득 차게 되면 운영체제는 추가적인 커넥션 요청을 거절하거나 커넥션이 timeout 될 수 있다.
    # 1 이라면 대기열에 보관될 수 있는 요청 수가 최대 1개라는 뜻.
    accept-count: 1
    # 서버가 시간 내에 수락&처리할 수 있는 최대 커넥션 개수
    # max-connection 에 도달하면 서버는 하나의 요청을 더 수락하지만, 처리하지는 않는다.
    # 처리중인 커넥션 수가 max-connection 아래로 떨어질 떄까지 추가 connection 은 막힌다.
    # 아래로 떨어질 경우 서버는 새 연결을 수락&처리한다.
    # 그러나 max-connections 에 도달하더라도 accept-count 설정에 따라 추가 connection 을 허용할 수 있다.
    max-connections: 2
    threads:
      # 커넥터에서 생성할 요청을 처리하는 스레드의 최대 수
      # = 처리할 수 있는 동시 요청의 최대 수
      # 만약 Excutor(실행기)가 이 커넥터와 연결된 경우 커넥터는 내부 스레드 풀이 아니라 실행기를 사용하여 작업을 실행하기 때문에 이 속성이 무시된다.
      # 실행기가 구성된 경우 이 속성이 사용되지 않음을 알리기 위해 -1 로 작성해두자.
      max: 2
      min-spare: 2

  compression:
    enabled: true
    min-response-size: 10
